### ISSUE TITLE
combined to scattered

### ISSUE THREAD

**Issue by ggggeneva** [ggggeneva/blueskywhitecloud#1]
I've positioned all the individual brush strokes for each character in their combined position, not sure how to start building the scattered state

**Comment by sehsarah** [comment]
Awesome! The way you can start to code up the "scattered" state, is via these 2 steps:
- manually add a class to the page element `bw-character--scattered`
- create CSS that positions brush strokes in different positions when they are inside `bw-character--scattered`

Does that make sense?

So without the class on the page element, your brush strokes will be combined
And with the class on the page element, your brush strokes will be scattered

Then after that, I can help you write a snippet that adds and removes this class depending on the hover action you have defined in your design

@ggggeneva let me know if you have more questions
@ellysmlly do u have anything to add?

**Comment by sehsarah** [comment]
Just had a look and you don't have a page element in your HTML right now, so you can either create that to wrap your page content, or you can apply the class to the `body` element https://github.com/ggggeneva/blueskywhitecloud/blob/main/index.html#L11

**Comment by ellysmlly** [comment]
Yeah awesome! Only note just incase I didn't cover it in class, is to add styles to your elements when a parent class is on your body the CSS will look like this 

```
.bw-character--scattered .bw-character--lan-1 {
    /* add CSS here */
}
```

Let me know if you have any questions with how to write it @ggggeneva

**Comment by ggggeneva** [comment]
Would I add a class to the body element like this? <body class="bw-character--scattered>
I gave it a little go but I don't think I get it/ am doing it right. I'm not sure how to position the brush strokes in the scattered state, do I just put in another <div class="bw-character--lan-1> with the png? so there's two of the same brush stroke but in different positions? I tried to do that but the new positioning would also change the existing combined position and the sizing was off because its currently sized in relation the the character container that it is in, but if I just put it in the body then it get sized to the page and ends up being too big. I think I will need you to talk me through starting it.
![image](https://user-images.githubusercontent.com/91919837/136140541-cd20dc2b-ad86-4552-be4e-529b0920e103.png)

**Comment by ellysmlly** [comment]
> Would I add a class to the body element like this? `<body class="bw-character--scattered">`

Yes thats perfect (i just added the missing end quote on the end of the class attribute)

> I gave it a little go but I don't think I get it/ am doing it right. I'm not sure how to position the brush strokes in the scattered state, do I just put in another <div class="bw-character--lan-1> with the png? so there's two of the same brush stroke but in different positions?

Ok cool good question, happy to chat through tomorrow in class but will note down how I would approach this personally:

1. Keep your same mark up and only have 1 image per stroke

2. To move each stroke in the 'scattered' state, use CSS `transform`

3. Apply the `transform` ONLY when the `bw-character--scattered` class is on the `body`
 
This will mean your image stays the same width in relation to its container, and you can control where it should move exactly from the position it is in when in combined state.

e.g.
`transform: translateX(100px);` would move your stroke to the right 100px
`transform: translateY(-100px);` would move your stroke up 100px
`transform: rotate(15deg);` would angle your stroke 15deg   

To combine all of these:
`transform: translateX(100px) translateY(-100px) rotate(15deg);` 

You are creating a scattered style for each stroke by moving them X and Y away from its final combined position.

Does that make sense?
