### ISSUE TITLE
on hover change form scattered to combined using my css class

### ISSUE THREAD

**Issue by ggggeneva** [ggggeneva/blueskywhitecloud#2]
I've positioned all the brush strokes in their scattered positions. 
I think the next step is how to make them move-
brushstrokes floating around the page and then move to the combined position on hover.

**Comment by ggggeneva** [comment]
I have done this now where all four characters combine when you hover on the first box using a small script

the next step will be combining only the first character and not all four
I will do this by creating a new css class that only combines character blue

**Comment by ggggeneva** [comment]
I've found an issue where the the hover works when you hover on the box and also when you hover over a brush stroke that belongs to that box in the combined position-
 i.e. if I hover over the first box, all the brush strokes for blue combine which is what I what but if I hover one of the blue brushstrokes while they are in the scattered position, they also combine. 
At first I though it was something I did wrong when I was separating each character, but I went back to github to check the code for when all four characters combine and it does the same thing.

**Comment by sehsarah** [comment]
awesome debugging @ggggeneva !! that's the perfect outline of recreation steps and testing - can help you out tomorrow

**Comment by ellysmlly** [comment]
awesome! I think this can be solved with CSS 

On your strokes class you can add the style `pointer-events: none;` in your css this means that this object will no longer interact with the mouse and so only the box will add the hover effect 

Try it out and let me know if that solves your issue

**Comment by ggggeneva** [comment]
yes! it worked :) @ellysmlly

**Comment by ggggeneva** [comment]
I found an issue when trying to remove the transition going back to the scattered state. 
`
.bw-character--scattered-blue * {
  transition: none;
}
`
I did the same thing as above for all four characters and it removed all transitions.
So I went back and just left the one for blue since it was working when we tested it, but I realised it only works for one character (blue) and also removes the transition for the other three characters so when you hover on it, it doesn't transition in, just appears like it did before.
@ellysmlly

**Comment by ellysmlly** [comment]
cool @ggggeneva i took a look and you just need to be more specific of when each character container needs the transition none property 

So your CSS should be updated to this:

```
.bw-character--scattered-blue .bw-character--blue * {
  transition: none;
}

.bw-character--scattered-sky .bw-character--sky * {
  transition: none;
}

.bw-character--scattered-white .bw-character--white * {
  transition: none;
}

.bw-character--scattered-cloud .bw-character--cloud * {
  transition: none;
}
```

**Comment by ellysmlly** [comment]
Do you think maybe its just a touch to slow at 6s?

**Comment by ggggeneva** [comment]
ok, that fixed the problem.
To make them all combine at the same time, I want to have one brushstroke (bw-character--yun-12) be clickable so that when you click on it, the transition will happen for all the characters. 
@sehsarah @ellysmlly

**Comment by sehsarah** [comment]
> I want to have one brushstroke be clickable

Is this meant to be a secret in the design because will people know which brushstroke to click to make that happen? Should it be more obvious?

Yes we can help you with that - is all your latest stuff uploaded onto Github right now? @ggggeneva

**Comment by ggggeneva** [comment]
yes my latest is uploaded. I was thinking there could be some sort of hint like maybe changing colour or adding an animation so it does a little wiggle, but I don't think I want it to be too hard to find

**Comment by sehsarah** [comment]
Ok cool both those options sound good, maybe colour changing is slightly more obvious that it's a "special" stroke

**Comment by sehsarah** [comment]
Realised you're going to have issues with making one of the brushstrokes detect click because you've turned off pointer events for all brush strokes to fix your hover issue in https://github.com/ggggeneva/blueskywhitecloud/issues/2#issuecomment-942132834

So might need another idea for what to click, but i made you an example snippet for this:

```
document.getElementById("special-brush-stroke").onclick = function(){
     document.body.classList.remove('bw-character--scattered-blue');
     document.body.classList.remove('bw-character--scattered-sky');
     document.body.classList.remove('bw-character--scattered-white');
     document.body.classList.remove('bw-character--scattered-cloud');
};
```
